// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetHealthCheckOKCode is the HTTP code returned for type GetHealthCheckOK
const GetHealthCheckOKCode int = 200

/*GetHealthCheckOK Server OK

swagger:response getHealthCheckOK
*/
type GetHealthCheckOK struct {
}

// NewGetHealthCheckOK creates GetHealthCheckOK with default headers values
func NewGetHealthCheckOK() *GetHealthCheckOK {

	return &GetHealthCheckOK{}
}

// WriteResponse to the client
func (o *GetHealthCheckOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
